### ISSUE TITLE
need help in getting location in background and kill mode.

### ISSUE THREAD

**Issue by thtRajasthaniGuy** [sslatif/react_native_background_location#1]
Hi,
see your project for getting location in the background, it is working?

**Comment by sslatif** [comment]
yes,  get location when app is in background is written in android & ios native part, but we can get it in raect-native by bridigng approach

**Comment by thtRajasthaniGuy** [comment]
from what I understand from the code after getting lat long you save the data in the db not sending it direct to the JS side.
and one more thing after stopping service the lat long is continuously saved in DB.

**Comment by thtRajasthaniGuy** [comment]
I want to only get the current location so can you help me out i remove all the db code but not able get current lat long.

**Comment by thtRajasthaniGuy** [comment]
libprocessgroup      com.ride360Driver      E  set_timerslack_ns write failed: Operation not permitted

it's throwing this error

when startLocationService clicked its goes else part but nothing happened, all permission is given, when I clone your project its worked fine, I implemented your code in my project nothing happened



                       @ReactMethod
                       public void startLocationService() {
                     if (Build.VERSION.SDK_INT <= Build.VERSION_CODES.P){
                     Log.e("startLocationService","clcked");
                    startService();
                    }
                  else {
                  Log.e("startLocation else","clcked");
                  ContextCompat.startForegroundService(getReactApplicationContext(), new Intent(getReactApplicationContext(), 
                 GoogleService.class));
                 }
                 }
                 
                 
its coming in else part ,i check with your code everything is correct, in your app its also coming in else part, but in my case
but not able to call googleservice file

**Comment by sslatif** [comment]
if you want to send location to java script check sendEvent function in google service.
NativeEventEmitter is used for this purpose study this.
I am sending location from native to reactnative through this feature.

If you want to write code in native and access it in react-native study React-bridging.
https://medium.com/simform-engineering/bridging-for-ios-and-android-in-react-native-64b8ce60a8c2

**Comment by sslatif** [comment]
if you want to send location to java script check sendEvent function in google service.
NativeEventEmitter is used for this purpose study this.
I am sending location from native to react-native through this feature.

If you want to write code in native and access it in react-native study React-bridging.
https://medium.com/simform-engineering/bridging-for-ios-and-android-in-react-native-64b8ce60a8c2

**Comment by thtRajasthaniGuy** [comment]
Thanks for help
